version: "3.8"

services:
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:8080"
  #   volumes:
  #     - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     - backend

  backend:
    build:
      context: ./Backend
    container_name: lms_backend
    command: >
      sh -c "gunicorn lms.wsgi --bind 0.0.0.0:8000 --log-file -"
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app:rw
    env_file:
      - ./backend-env
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    container_name: pgdb
    restart: always
    env_file:
      - ./pgdb-env
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  pgdata:
