# Generated by Django 3.2.5 on 2021-07-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
