# Generated by Django 3.2.5 on 2021-07-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loan_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='duration in month(s)'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.FloatField(verbose_name='Rate of interest'),
        ),
    ]
